# Generated by Django 4.1.4 on 2023-08-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=40)),
                ('last_name', models.CharField(default='lastname', max_length=40)),
                ('email', models.CharField(default='email', max_length=100)),
                ('mobile', models.CharField(default='0000', max_length=40)),
                ('password', models.CharField(default='password', max_length=40)),
            ],
        ),
    ]
