# Generated by Django 4.1.4 on 2023-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='movie name', max_length=150)),
                ('language', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=30)),
                ('year', models.CharField(default='', max_length=10)),
                ('pic', models.ImageField(default='static/images/movielogo.png', upload_to='siteadmin/')),
                ('video', models.FileField(default='static/images/movielogo.png', upload_to='siteadmin/')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
